name: dronecan
on: [push]
jobs:
  dronecan:
    strategy:
      matrix:
        target: [dronecan, sitl_dronecan]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # fetch all history for all branches and tags
          token: ${{ secrets.VTOL_PMU_IOC_TOKEN }}

      - name: Install dependencies
        run: ./scripts/tools/install_for_ubuntu.sh --yes

      - name: Install raccoonlab-tools
        run: |
          pip install pyserial python-can pydronecan pycyphal pytest pytest-asyncio yakut
          pip install -i https://test.pypi.org/simple/ raccoonlab-tools

      - name: Build the target
        run: make ${{ matrix.target }}

      - name: If SITL then run and execute pytest tests
        if: ${{ matrix.target == 'sitl_dronecan' }}
        run: |
          make run &
          rl-test-dronecan-specification
